[package]
name = "wirehair"
version = "0.1.0"
edition = "2024"
keywords = ["FEC", "forward error correction", "wirehair"]
description = "WireHair Forward Error Correction"
repository = "https://github.com/daibo83/wirehair-rs"
license = "MIT"

[dependencies]
gf256 = "0.3.1"
